{
  "$GMRoomUI":"",
  "%Name":"RoomUI",
  "children":[
    {"$GMRUILayer":"v1","%Name":"UILayer_1","alignItems":2,"children":[
        {"$GMRInstance":"v4","%Name":"inst_6DB5E110","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_6DB5E110","objectId":{"name":"o_ui_display","path":"objects/o_ui_display/o_ui_display.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":512.0,"y":-448.0,},
        {"$GMRInstance":"v4","%Name":"inst_2214236D","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_2214236D","objectId":{"name":"o_ui_element","path":"objects/o_ui_element/o_ui_element.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":13.125,"scaleY":15.4375,"x":-470.0,"y":-123.5,},
        {"$GMRInstance":"v4","%Name":"inst_635BF181","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_635BF181","objectId":{"name":"o_single_cycle_isr","path":"objects/o_single_cycle_isr/o_single_cycle_isr.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":98.0,"y":91.5,},
        {"$GMRInstance":"v4","%Name":"inst_3BC378F6","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_3BC378F6","objectId":{"name":"o_light_armor","path":"objects/o_light_armor/o_light_armor.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":297.25,"y":91.5,},
        {"$GMRInstance":"v4","%Name":"inst_45519356","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_45519356","objectId":{"name":"o_standardized_replicator","path":"objects/o_standardized_replicator/o_standardized_replicator.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":169.25,"y":91.5,},
        {"$GMRInstance":"v4","%Name":"inst_64CEA559","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_64CEA559","objectId":{"name":"o_ballistic_tip","path":"objects/o_ballistic_tip/o_ballistic_tip.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":361.25,"y":91.5,},
        {"$GMRInstance":"v4","%Name":"inst_74ECE3B0","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_74ECE3B0","objectId":{"name":"o_combat_log","path":"objects/o_combat_log/o_combat_log.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":864.0,"y":72.0,},
        {"$GMRInstance":"v4","%Name":"inst_3493639","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_3493639","objectId":{"name":"o_deckbg","path":"objects/o_deckbg/o_deckbg.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":33.125,"scaleY":5.875,"x":754.0,"y":943.0,},
        {"$GMRInstance":"v4","%Name":"inst_4BAB9A92","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_4BAB9A92","objectId":{"name":"o_energy","path":"objects/o_energy/o_energy.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":3.5546875,"scaleY":3.5546875,"x":347.0,"y":786.25,},
        {"$GMRInstance":"v4","%Name":"inst_6DC60599","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_6DC60599","objectId":{"name":"o_multi_role_tanker_transport","path":"objects/o_multi_role_tanker_transport/o_multi_role_tanker_transport.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":233.25,"y":91.5,},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":1,"name":"UILayer_1","nodeColour":4291359304,"resourceType":"GMRUILayer","resourceVersion":"2.0",},
  ],
  "locked":false,
  "name":"RoomUI",
  "parent":{
    "name":"BLANK GAME",
    "path":"BLANK GAME.yyp",
  },
  "resourceType":"GMRoomUI",
  "resourceVersion":"2.0",
  "viewspaceChildren":[],
  "visible":true,
}